### Register: đăng ký tài khoản, trả về accessToken và refreshToken để client ghi nhận và sử dụng cho các lần gửi request tiếp theo
# URL: ${protocol}://${hostname}/api/v1/auth/register
# headers: {
#   Content-Type: application/json;
#}
# body: {
#   "fullname": String,
#   "email": String,
#   "password": String
#}
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "fullname": "Nguyễn Như Việt",
    "email": "test3@gmail.com",
    "password": "12345"
}


### Register: đăng nhập, trả về accessToken và refreshToken để client ghi nhận và sử dụng cho các lần gửi request tiếp theo
# URL: ${protocol}://${hostname}/api/v1/auth/login
# headers: {
#   Content-Type: application/json;
#}
# body: {
#   "email": String,
#   "password": String
#}
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "a1@gmail.com",
    "password": "resetpass"
}


### Refesh token: lấy lại accessToken để duy trì trạng thái đăng nhập của tài khoản (accessToken có thời hạn 15p) 
# URL: ${protocol}://${hostname}/api/v1/auth/refresh-token
# headers: {
#   Content-Type: application/json;
#}
# body: {
#   "refreshToken": String,
#}
POST http://localhost:5000/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYjM1ZTllYjk0YmIzMGVmZjNjMmU1NiIsImlhdCI6MTY1NTkyMzcwNiwiZXhwIjoxNjYzNjk5NzA2fQ.0ytfRTGlwDZlHNAPQsFVgLQCYnqxE7lZrdLeV0efB8c"
}


### View user profile: xem thông tin tài khoản, cần cung cấp accessToken để có thể truy cập được API này
# URL: ${protocol}://${hostname}/api/v1/auth/refresh-token
# headers: {
#   Content-Type: application/json;
#   Authorization: Bearer + " " + ${accessToken}
#}
# body: {}
GET http://localhost:5000/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYjk3NGY0ZDNkZTgzOWMwMDRiZTA4OSIsImlhdCI6MTY1NjYwMTY0NSwiZXhwIjoxNjU2NjAyNTQ1fQ.dpzgD4t3yfbd_hnm0XP6A-DVBIBjLupIzeKEtpP-SOs



### Update user profile: sửa thông tin tài khoản, cần cung cấp accessToken để có thể truy cập được API này
# URL: ${protocol}://${hostname}/api/v1/users/me
# headers: {
#   Content-Type: application/json;
#   Authorization: Bearer + " " + ${accessToken}
#}
# body: {
    // các trường dữ liệu cần update
#}
PATCH http://localhost:5000/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYjk3NGY0ZDNkZTgzOWMwMDRiZTA4OSIsImlhdCI6MTY1NjYwMTY0NSwiZXhwIjoxNjU2NjAyNTQ1fQ.dpzgD4t3yfbd_hnm0XP6A-DVBIBjLupIzeKEtpP-SOs
Content-Type: application/json

{
    "fullname": "Nguyễn Văn A",
    "phoneNumber": "0123456789",
    "birthDay": "2001-06-05T23:15:30.000Z",
    "address": {
        "street": "53 Hoàng Việt",
        "wards": "Phường 4",
        "district": "Tân Bình",
        "city": "TP.HCM"
    }
}

### Forgot user password: lấy lại mật khẩu trong trường hợp quên mật khẩu,
#                        gửi link reset mật khẩu qua email
# URL: ${protocol}://${hostname}/api/v1/users/forgot-password
# headers: {
#   Content-Type: application/json;
#}
# body: {
#   "email": String
#}
POST http://localhost:5000/api/v1/users/forgot-password
Content-Type: application/json

    {
        "email": "a1@gmail.com"
    }


### Reset password: Sau khi nhận được mail chứa link reset, user bám vào link và nhập lại mật khẩu mới
#                  server ghi nhận lại mật khẩu mới và trả về accessToken và refreshToken mới
# URL: ${protocol}://${hostname}/api/v1/users/reset-password/${resetPasswordToken}
# headers: {
#   Content-Type: application/json;
#}
# body: {
#   "password": String
#}
PATCH http://localhost:5000/api/v1/users/reset-password/dc8e5632d4d6460eddba41dbb1470a75ad46b9ec9287b47533616a5833ef8edd
Content-Type: application/json

{
    "password": "resetpass"
}


###### Start a chat with anyone: tìm user theo tên -> trả về id user nếu có -> gửi req lên để tạo 1 room chat với user id đó
##1. Find users by name
GET http://localhost:5000/api/v1/users/find/Ha%20Duyen%20Thang
Content-Type: application/json; charset=utf-8